# -*- coding: utf-8 -*-
"""辞書機能のデコード

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IZJhFPsakCJj8YZRaL0VhanrhQ0EUVPl
"""

#{kindから始まる文字列を代入しろぼけ
#sample {"kind": "com.kuroneko6423.kuronekottsbot.dictionary", "version": 0, "data": {"\u4e0b\u95a2": "\u3057\u3082\u306e\u305b\u304d", "\ud83d\udc40": "\u3081", "\u53d9\u3005\u82d1": "\u3058\u3087\u3058\u3087\u3048\u3093", "\u5948\u4e43": "\u306a\u306e"}}
moji = input("文字列を入力 : ")
#余計なとこ消し飛ばす "{" がないと止まらない
moji = moji.lstrip(moji[0])
while moji[0] != ("{"):
  moji = moji.lstrip(moji[0])

#print (moji)

#結果の変数をコピーしてUnicodeに変換する
#↑何言いたいのか理解できない
n = 0 
result = ("")
while moji[n] != ("}"):
    
    while moji[n] != ("\\"):
      n+=1
    while moji[n] != ("\""):
      result = result + moji[n]
      n+=1
    result = result + (" ")
    n+=1

print (result)

